version: '3.9'

services:
  web:
    build: .
    command: sh -c "gunicorn trafficlight.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  celery:
    build: .
    command: celery -A trafficlight worker --loglevel=info
    volumes:
      - .:/app

    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A trafficlight beat --loglevel=info
    volumes:
      - .:/app
   
    env_file:
      - .env

volumes:
  postgres_data:
