# Generated by Django 4.2.13 on 2024-06-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JumlahKendaraan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jalan', models.CharField(max_length=100)),
                ('jam', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('jumlah', models.IntegerField()),
                ('jenis', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
